platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
  pod 'PromiseKit', '~> 3'
end

target 'AwaitedPromiseKit' do
  shared_pods
end

target 'AwaitedPromiseKitTests' do
  shared_pods
end
