platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
  pod 'PromiseKit', :git => 'https://github.com/yannickl/PromiseKit'
end

target 'AwaitKitExample' do
  shared_pods
end

target 'AwaitKitTests' do
  shared_pods
  
  pod 'AwaitKit', :path => '../'
end
